directories:
  output: dist_electron
  buildResources: assets
appId: com.my-website.my-app
productName: MyApp
copyright: Copyright © 2021 kuari
mac:
  category: public.app-category.utilities
nsis:
  oneClick: false
  allowToChangeInstallationDirectory: true
files:
  - filter:
      - dist/**/*
      - electron/**/*
electronVersion: 23.2.0
